/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface DaoCallsDebugger extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): DaoCallsDebugger;
  clone(): DaoCallsDebugger;
  methods: {
    countVotes(
      dao: string,
      proposalId: number | string | BN
    ): NonPayableTransactionObject<[string, string, string, string]>;

    getActiveProposalIds(dao: string): NonPayableTransactionObject<string[]>;

    getDaoEpochTotalStakeSnapshot(
      dao: string,
      daoPhaseCount: number | string | BN
    ): NonPayableTransactionObject<string>;

    getProposalDaoPhaseCount(
      dao: string,
      proposalId: number | string | BN
    ): NonPayableTransactionObject<string>;

    getProposalFee(
      dao: string,
      proposalId: number | string | BN
    ): NonPayableTransactionObject<string>;

    getProposalProposer(
      dao: string,
      proposalId: number | string | BN
    ): NonPayableTransactionObject<string>;

    getProposalState(
      dao: string,
      proposalId: number | string | BN
    ): NonPayableTransactionObject<string>;

    getProposalType(
      dao: string,
      proposalId: number | string | BN
    ): NonPayableTransactionObject<string>;

    getProposalVoters(
      dao: string,
      proposalId: number | string | BN
    ): NonPayableTransactionObject<string[]>;

    getProposalVotersCount(
      dao: string,
      proposalId: number | string | BN
    ): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
