/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type Initialized = ContractEventLog<{
  version: string;
  0: string;
}>;
export type NameChanged = ContractEventLog<{
  node: string;
  name: string;
  0: string;
  1: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;

export interface DiamondRegistry extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): DiamondRegistry;
  clone(): DiamondRegistry;
  methods: {
    MAX_NAME_LENGHT(): NonPayableTransactionObject<string>;

    MIN_NAME_LENGTH(): NonPayableTransactionObject<string>;

    addr(node: string | number[]): NonPayableTransactionObject<string>;

    available(_name: string): NonPayableTransactionObject<boolean>;

    costs(arg0: string): NonPayableTransactionObject<string>;

    getAddressOfName(_name: string): NonPayableTransactionObject<string>;

    getHashOfName(_name: string): NonPayableTransactionObject<string>;

    getHashOfNameBytes(
      _name: string | number[]
    ): NonPayableTransactionObject<string>;

    getSetNameCost(node: string): NonPayableTransactionObject<string>;

    initialize(_reinsertPotAddress: string): NonPayableTransactionObject<void>;

    maximumCosts(): NonPayableTransactionObject<string>;

    name(node: string): NonPayableTransactionObject<string>;

    names(arg0: string): NonPayableTransactionObject<string>;

    namesReverse(arg0: string | number[]): NonPayableTransactionObject<string>;

    owner(): NonPayableTransactionObject<string>;

    reinsertPotAddress(): NonPayableTransactionObject<string>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    setOwnName(_name: string): PayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    valid(_name: string): NonPayableTransactionObject<boolean>;
  };
  events: {
    Initialized(cb?: Callback<Initialized>): EventEmitter;
    Initialized(
      options?: EventOptions,
      cb?: Callback<Initialized>
    ): EventEmitter;

    NameChanged(cb?: Callback<NameChanged>): EventEmitter;
    NameChanged(
      options?: EventOptions,
      cb?: Callback<NameChanged>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "Initialized", cb: Callback<Initialized>): void;
  once(
    event: "Initialized",
    options: EventOptions,
    cb: Callback<Initialized>
  ): void;

  once(event: "NameChanged", cb: Callback<NameChanged>): void;
  once(
    event: "NameChanged",
    options: EventOptions,
    cb: Callback<NameChanged>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;
}
