/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type Initialized = ContractEventLog<{
  version: string;
  0: string;
}>;
export type NameActivated = ContractEventLog<{
  owner: string;
  labelHash: string;
  name: string;
  0: string;
  1: string;
  2: string;
}>;
export type NameBlockedSet = ContractEventLog<{
  labelHash: string;
  name: string;
  blocked: boolean;
  0: string;
  1: string;
  2: boolean;
}>;
export type NameDeactivated = ContractEventLog<{
  owner: string;
  labelHash: string;
  name: string;
  0: string;
  1: string;
  2: string;
}>;
export type NameRegistered = ContractEventLog<{
  node: string;
  labelHash: string;
  expiration: string;
  name: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;
export type NameRenewed = ContractEventLog<{
  owner: string;
  labelHash: string;
  expiration: string;
  name: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;
export type RemoveChangeableParameter = ContractEventLog<{
  funcSelector: string;
  0: string;
}>;
export type SetChangeableParameter = ContractEventLog<{
  setter: string;
  getter: string;
  params: string[];
  0: string;
  1: string;
  2: string[];
}>;
export type SetMintingFee = ContractEventLog<{
  value: string;
  0: string;
}>;

export interface DMDRegistrarController extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): DMDRegistrarController;
  clone(): DMDRegistrarController;
  methods: {
    ACTIVATION_FEE_DENOMINATOR(): NonPayableTransactionObject<string>;

    BASE_MINTING_FEE(): NonPayableTransactionObject<string>;

    DEFAULT_MINTING_FEE(): NonPayableTransactionObject<string>;

    DMD_TLD(): NonPayableTransactionObject<string>;

    EXPIRATION_TIME_YEARS(): NonPayableTransactionObject<string>;

    MAX_ACTIVATION_FEE_NUMERATOR(): NonPayableTransactionObject<string>;

    MAX_NAME_LENGTH(): NonPayableTransactionObject<string>;

    MIN_NAME_LENGTH(): NonPayableTransactionObject<string>;

    TRANSFER_FEE_DENOMINATOR(): NonPayableTransactionObject<string>;

    TRANSFER_FEE_NUMERATOR(): NonPayableTransactionObject<string>;

    activate(_name: string): PayableTransactionObject<void>;

    activations(arg0: string): NonPayableTransactionObject<string>;

    available(_name: string): NonPayableTransactionObject<boolean>;

    blockName(_name: string, _owner: string): NonPayableTransactionObject<void>;

    diamondNames(): NonPayableTransactionObject<string>;

    getActivationFee(_who: string): NonPayableTransactionObject<string>;

    getAllowedParamsRange(
      _selector: string
    ): NonPayableTransactionObject<[string, string[]]>;

    getAllowedParamsRangeWithSelector(
      _selector: string | number[]
    ): NonPayableTransactionObject<[string, string[]]>;

    getHashOfName(_name: string): NonPayableTransactionObject<string>;

    initialize(
      _initialOwner: string,
      _reinsertPot: string,
      _diamondNames: string,
      _registry: string,
      _resolver: string
    ): NonPayableTransactionObject<void>;

    isNameBlocked(_name: string): NonPayableTransactionObject<boolean>;

    isWithinAllowedRange(
      funcSelector: string | number[],
      newVal: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    mintingFee(): NonPayableTransactionObject<string>;

    names(arg0: string): NonPayableTransactionObject<string>;

    namesReverse(arg0: string | number[]): NonPayableTransactionObject<string>;

    owner(): NonPayableTransactionObject<string>;

    register(_name: string): PayableTransactionObject<void>;

    registry(): NonPayableTransactionObject<string>;

    reinsertPot(): NonPayableTransactionObject<string>;

    removeAllowedChangeableParameter(
      funcSelector: string | number[]
    ): NonPayableTransactionObject<void>;

    renew(_name: string): NonPayableTransactionObject<void>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    resetRecordsOnTransfer(
      _from: string,
      _tokenId: number | string | BN
    ): NonPayableTransactionObject<void>;

    resolver(): NonPayableTransactionObject<string>;

    setAllowedChangeableParameter(
      setter: string | number[],
      getter: string | number[],
      params: (number | string | BN)[]
    ): NonPayableTransactionObject<void>;

    setMintingFee(
      _value: number | string | BN
    ): NonPayableTransactionObject<void>;

    setNameBlocked(
      _name: string,
      _blocked: boolean
    ): NonPayableTransactionObject<void>;

    setNamesBlocked(
      _names: string[],
      _blocked: boolean
    ): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    valid(_name: string): NonPayableTransactionObject<boolean>;
  };
  events: {
    Initialized(cb?: Callback<Initialized>): EventEmitter;
    Initialized(
      options?: EventOptions,
      cb?: Callback<Initialized>
    ): EventEmitter;

    NameActivated(cb?: Callback<NameActivated>): EventEmitter;
    NameActivated(
      options?: EventOptions,
      cb?: Callback<NameActivated>
    ): EventEmitter;

    NameBlockedSet(cb?: Callback<NameBlockedSet>): EventEmitter;
    NameBlockedSet(
      options?: EventOptions,
      cb?: Callback<NameBlockedSet>
    ): EventEmitter;

    NameDeactivated(cb?: Callback<NameDeactivated>): EventEmitter;
    NameDeactivated(
      options?: EventOptions,
      cb?: Callback<NameDeactivated>
    ): EventEmitter;

    NameRegistered(cb?: Callback<NameRegistered>): EventEmitter;
    NameRegistered(
      options?: EventOptions,
      cb?: Callback<NameRegistered>
    ): EventEmitter;

    NameRenewed(cb?: Callback<NameRenewed>): EventEmitter;
    NameRenewed(
      options?: EventOptions,
      cb?: Callback<NameRenewed>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    RemoveChangeableParameter(
      cb?: Callback<RemoveChangeableParameter>
    ): EventEmitter;
    RemoveChangeableParameter(
      options?: EventOptions,
      cb?: Callback<RemoveChangeableParameter>
    ): EventEmitter;

    SetChangeableParameter(cb?: Callback<SetChangeableParameter>): EventEmitter;
    SetChangeableParameter(
      options?: EventOptions,
      cb?: Callback<SetChangeableParameter>
    ): EventEmitter;

    SetMintingFee(cb?: Callback<SetMintingFee>): EventEmitter;
    SetMintingFee(
      options?: EventOptions,
      cb?: Callback<SetMintingFee>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "Initialized", cb: Callback<Initialized>): void;
  once(
    event: "Initialized",
    options: EventOptions,
    cb: Callback<Initialized>
  ): void;

  once(event: "NameActivated", cb: Callback<NameActivated>): void;
  once(
    event: "NameActivated",
    options: EventOptions,
    cb: Callback<NameActivated>
  ): void;

  once(event: "NameBlockedSet", cb: Callback<NameBlockedSet>): void;
  once(
    event: "NameBlockedSet",
    options: EventOptions,
    cb: Callback<NameBlockedSet>
  ): void;

  once(event: "NameDeactivated", cb: Callback<NameDeactivated>): void;
  once(
    event: "NameDeactivated",
    options: EventOptions,
    cb: Callback<NameDeactivated>
  ): void;

  once(event: "NameRegistered", cb: Callback<NameRegistered>): void;
  once(
    event: "NameRegistered",
    options: EventOptions,
    cb: Callback<NameRegistered>
  ): void;

  once(event: "NameRenewed", cb: Callback<NameRenewed>): void;
  once(
    event: "NameRenewed",
    options: EventOptions,
    cb: Callback<NameRenewed>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;

  once(
    event: "RemoveChangeableParameter",
    cb: Callback<RemoveChangeableParameter>
  ): void;
  once(
    event: "RemoveChangeableParameter",
    options: EventOptions,
    cb: Callback<RemoveChangeableParameter>
  ): void;

  once(
    event: "SetChangeableParameter",
    cb: Callback<SetChangeableParameter>
  ): void;
  once(
    event: "SetChangeableParameter",
    options: EventOptions,
    cb: Callback<SetChangeableParameter>
  ): void;

  once(event: "SetMintingFee", cb: Callback<SetMintingFee>): void;
  once(
    event: "SetMintingFee",
    options: EventOptions,
    cb: Callback<SetMintingFee>
  ): void;
}
