/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type ApprovalForAll = ContractEventLog<{
  owner: string;
  operator: string;
  approved: boolean;
  0: string;
  1: string;
  2: boolean;
}>;
export type Initialized = ContractEventLog<{
  version: string;
  0: string;
}>;
export type NewOwner = ContractEventLog<{
  node: string;
  label: string;
  owner: string;
  0: string;
  1: string;
  2: string;
}>;
export type NewResolver = ContractEventLog<{
  node: string;
  resolver: string;
  0: string;
  1: string;
}>;
export type NewTTL = ContractEventLog<{
  node: string;
  ttl: string;
  0: string;
  1: string;
}>;
export type Transfer = ContractEventLog<{
  node: string;
  owner: string;
  0: string;
  1: string;
}>;

export interface DMDRegistry extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): DMDRegistry;
  clone(): DMDRegistry;
  methods: {
    initialize(_rootOwner: string): NonPayableTransactionObject<void>;

    isApprovedForAll(
      _owner: string,
      _operator: string
    ): NonPayableTransactionObject<boolean>;

    owner(_node: string | number[]): NonPayableTransactionObject<string>;

    recordExists(
      _node: string | number[]
    ): NonPayableTransactionObject<boolean>;

    resolver(_node: string | number[]): NonPayableTransactionObject<string>;

    setApprovalForAll(
      _operator: string,
      _approved: boolean
    ): NonPayableTransactionObject<void>;

    setOwner(
      _node: string | number[],
      _owner: string
    ): NonPayableTransactionObject<void>;

    setRecord(
      _node: string | number[],
      _owner: string,
      _resolver: string,
      _ttl: number | string | BN
    ): NonPayableTransactionObject<void>;

    setResolver(
      _node: string | number[],
      _resolver: string
    ): NonPayableTransactionObject<void>;

    setSubnodeOwner(
      _node: string | number[],
      _label: string | number[],
      _owner: string
    ): NonPayableTransactionObject<string>;

    setSubnodeRecord(
      _node: string | number[],
      _label: string | number[],
      _owner: string,
      _resolver: string,
      _ttl: number | string | BN
    ): NonPayableTransactionObject<void>;

    setTTL(
      _node: string | number[],
      _ttl: number | string | BN
    ): NonPayableTransactionObject<void>;

    ttl(_node: string | number[]): NonPayableTransactionObject<string>;
  };
  events: {
    ApprovalForAll(cb?: Callback<ApprovalForAll>): EventEmitter;
    ApprovalForAll(
      options?: EventOptions,
      cb?: Callback<ApprovalForAll>
    ): EventEmitter;

    Initialized(cb?: Callback<Initialized>): EventEmitter;
    Initialized(
      options?: EventOptions,
      cb?: Callback<Initialized>
    ): EventEmitter;

    NewOwner(cb?: Callback<NewOwner>): EventEmitter;
    NewOwner(options?: EventOptions, cb?: Callback<NewOwner>): EventEmitter;

    NewResolver(cb?: Callback<NewResolver>): EventEmitter;
    NewResolver(
      options?: EventOptions,
      cb?: Callback<NewResolver>
    ): EventEmitter;

    NewTTL(cb?: Callback<NewTTL>): EventEmitter;
    NewTTL(options?: EventOptions, cb?: Callback<NewTTL>): EventEmitter;

    Transfer(cb?: Callback<Transfer>): EventEmitter;
    Transfer(options?: EventOptions, cb?: Callback<Transfer>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "ApprovalForAll", cb: Callback<ApprovalForAll>): void;
  once(
    event: "ApprovalForAll",
    options: EventOptions,
    cb: Callback<ApprovalForAll>
  ): void;

  once(event: "Initialized", cb: Callback<Initialized>): void;
  once(
    event: "Initialized",
    options: EventOptions,
    cb: Callback<Initialized>
  ): void;

  once(event: "NewOwner", cb: Callback<NewOwner>): void;
  once(event: "NewOwner", options: EventOptions, cb: Callback<NewOwner>): void;

  once(event: "NewResolver", cb: Callback<NewResolver>): void;
  once(
    event: "NewResolver",
    options: EventOptions,
    cb: Callback<NewResolver>
  ): void;

  once(event: "NewTTL", cb: Callback<NewTTL>): void;
  once(event: "NewTTL", options: EventOptions, cb: Callback<NewTTL>): void;

  once(event: "Transfer", cb: Callback<Transfer>): void;
  once(event: "Transfer", options: EventOptions, cb: Callback<Transfer>): void;
}
