/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type AddrChanged = ContractEventLog<{
  node: string;
  a: string;
  0: string;
  1: string;
}>;
export type Initialized = ContractEventLog<{
  version: string;
  0: string;
}>;
export type NameChanged = ContractEventLog<{
  node: string;
  name: string;
  0: string;
  1: string;
}>;

export interface DMDResolver extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): DMDResolver;
  clone(): DMDResolver;
  methods: {
    addr(node: string | number[]): NonPayableTransactionObject<string>;

    addresses(arg0: string | number[]): NonPayableTransactionObject<string>;

    initialize(_registry: string): NonPayableTransactionObject<void>;

    name(node: string | number[]): NonPayableTransactionObject<string>;

    names(arg0: string | number[]): NonPayableTransactionObject<string>;

    registry(): NonPayableTransactionObject<string>;

    setAddr(
      node: string | number[],
      a: string
    ): NonPayableTransactionObject<void>;

    setName(
      node: string | number[],
      newName: string
    ): NonPayableTransactionObject<void>;

    supportsInterface(
      interfaceId: string | number[]
    ): NonPayableTransactionObject<boolean>;
  };
  events: {
    AddrChanged(cb?: Callback<AddrChanged>): EventEmitter;
    AddrChanged(
      options?: EventOptions,
      cb?: Callback<AddrChanged>
    ): EventEmitter;

    Initialized(cb?: Callback<Initialized>): EventEmitter;
    Initialized(
      options?: EventOptions,
      cb?: Callback<Initialized>
    ): EventEmitter;

    NameChanged(cb?: Callback<NameChanged>): EventEmitter;
    NameChanged(
      options?: EventOptions,
      cb?: Callback<NameChanged>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "AddrChanged", cb: Callback<AddrChanged>): void;
  once(
    event: "AddrChanged",
    options: EventOptions,
    cb: Callback<AddrChanged>
  ): void;

  once(event: "Initialized", cb: Callback<Initialized>): void;
  once(
    event: "Initialized",
    options: EventOptions,
    cb: Callback<Initialized>
  ): void;

  once(event: "NameChanged", cb: Callback<NameChanged>): void;
  once(
    event: "NameChanged",
    options: EventOptions,
    cb: Callback<NameChanged>
  ): void;
}
