/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface IDaoAccessors extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): IDaoAccessors;
  clone(): IDaoAccessors;
  methods: {
    countVotes(proposalId: number | string | BN): NonPayableTransactionObject<{
      countYes: string;
      countNo: string;
      stakeYes: string;
      stakeNo: string;
      0: string;
      1: string;
      2: string;
      3: string;
    }>;

    daoEpochTotalStakeSnapshot(
      daoPhaseCount: number | string | BN
    ): NonPayableTransactionObject<string>;

    getCurrentPhaseProposals(): NonPayableTransactionObject<string[]>;

    getProposalVoters(
      proposalId: number | string | BN
    ): NonPayableTransactionObject<string[]>;

    getProposalVotersCount(
      proposalId: number | string | BN
    ): NonPayableTransactionObject<string>;

    proposals(proposalId: number | string | BN): NonPayableTransactionObject<{
      proposer: string;
      votingDaoEpoch: string;
      state: string;
      title: string;
      description: string;
      discussionUrl: string;
      daoPhaseCount: string;
      proposalFee: string;
      proposalType: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: string;
      6: string;
      7: string;
      8: string;
    }>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
