import { Validator } from './types';

export const mockValidators: Validator[] = [
  {
    id: '1',
    status: 'active',
    walletAddress: '0x7a2D...3F5e',
    minerAddress: '0x8b3F...2A7c',
    publicKey: 'BHr9x...k7Yz',
    totalStake: '1,250,000 DMD',
    votingPower: '4.2%',
    score: 987,
    cr: 0,
    myStake: '0 DMD',
    canStake: true,
    canUnstake: false
  },
  {
    id: '2',
    status: 'active',
    walletAddress: '0x3B1c...9D2a',
    minerAddress: '0x9c4A...1E8d',
    publicKey: 'CFi2y...m6Xw',
    totalStake: '980,500 DMD',
    votingPower: '3.3%',
    score: 991,
    cr: 12,
    myStake: '5,000 DMD',
    canStake: true,
    canUnstake: true
  },
  {
    id: '3',
    status: 'valid',
    walletAddress: '0xF42e...1A7b',
    minerAddress: '0x2d7B...5C9e',
    publicKey: 'GLa5z...p8Rq',
    totalStake: '750,200 DMD',
    votingPower: '2.5%',
    score: 975,
    cr: 0,
    myStake: '0 DMD',
    canStake: true,
    canUnstake: false
  },
  {
    id: '4',
    status: 'invalid',
    walletAddress: '0x8D5f...6E4c',
    minerAddress: '0x6e1C...7F3a',
    publicKey: 'AKw8v...u2Zs',
    totalStake: '420,800 DMD',
    votingPower: '1.4%',
    score: 853,
    cr: 36,
    myStake: '0 DMD',
    canStake: false,
    canUnstake: false
  },
  {
    id: '5',
    status: 'active',
    walletAddress: '0x2C9a...5B3d',
    minerAddress: '0x1f8D...9B4c',
    publicKey: 'DMy4x...q1Vt',
    totalStake: '1,120,600 DMD',
    votingPower: '3.8%',
    score: 989,
    cr: 8,
    myStake: '2,500 DMD',
    canStake: true,
    canUnstake: true
  },
  {
    id: '6',
    status: 'active',
    walletAddress: '0x9A3d...7C4e',
    minerAddress: '0x5a2E...3D6f',
    publicKey: 'JOp7b...r9Yn',
    totalStake: '890,700 DMD',
    votingPower: '3.0%',
    score: 993,
    cr: 0,
    myStake: '0 DMD',
    canStake: true,
    canUnstake: false
  },
  {
    id: '7',
    status: 'valid',
    walletAddress: '0x4D2e...8F5a',
    minerAddress: '0x7c9F...4E1a',
    publicKey: 'LTw1h...s5Xo',
    totalStake: '680,300 DMD',
    votingPower: '2.3%',
    score: 978,
    cr: 3,
    myStake: '0 DMD',
    canStake: true,
    canUnstake: false
  },
  {
    id: '8',
    status: 'active',
    walletAddress: '0x1B5c...3A7d',
    minerAddress: '0x3b6A...8C2b',
    publicKey: 'QRs3k...t7Zm',
    totalStake: '1,050,800 DMD',
    votingPower: '3.5%',
    score: 985,
    cr: 18,
    myStake: '3,000 DMD',
    canStake: true,
    canUnstake: true
  },
  {
    id: '9',
    status: 'invalid',
    walletAddress: '0x5E8f...2D6b',
    minerAddress: '0x4d5B...6A9c',
    publicKey: 'YZv6n...w4Up',
    totalStake: '290,500 DMD',
    votingPower: '1.0%',
    score: 827,
    cr: 42,
    myStake: '0 DMD',
    canStake: false,
    canUnstake: false
  }
];